---
name: Dart CI - Package Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: Start Job
        uses: actions/checkout@v1
      - name: Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: "*"
      - name: Pub.dev Release
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: false
